# Theme, mu-plugin and plugins live in /opt and are symlinked into wp-content.
<Directory /opt/>
	Options FollowSymLinks
	AllowOverride None
	Require all granted
</Directory>
DocumentRoot ${DEMO_ROOT}
<Directory ${DEMO_ROOT}>
	Options FollowSymLinks
	AllowOverride All
	Require all granted
</Directory>
ServerTokens Prod
ServerSignature Off
LimitRequestFieldSize 16384
